name: Node CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 14.x
      - name: Run tests
        run: |
          yarn install
          yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 14.x
      - name: Check codestyle
        run: |
          yarn install
          yarn lint:code
          yarn lint:styles
